os:
  - linux
  - osx
language: node_js
node_js:
  - 0.10
  - 0.12
  - 4.0
  - 4.1
  - 4.5
  - 5.0
  - 5.5
  - 5.12
  - 6
  - 6.6
  - node
  - lts/argon
  - lts/*
  - iojs
install: npm install
before_script:
  - "npm install -g grunt-cli"
  - "grunt build"
after_success:
  -  ./node_modules/.bin/jscoverage lib lib-cov
  - COV=1 ./node_modules/.bin/mocha test/**.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
