os:
  - linux
  - osx
language: node_js
node_js:
  - 4.0
  - 4.1
  - 4.5
  - 5.0
  - 5.5
  - 5.12
  - 6
  - 6.6
  - 7
  - 8
  - 9
  - node
  - lts/argon
  - lts/boron
  - lts/carbon
  - lts/*
after_success:
  - ./node_modules/.bin/istanbul report text-summary lcov
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
